// import { Geist, Geist_Mono } from "next/font/google";
import BootstrapClient from '@/BootstrapClient'
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import Navbar from "./Component/Navbar/Navbar";
import Footer from "./Component/Footer/Footer";
import { Inter, Nunito, Work_Sans } from 'next/font/google';
import { CartProvider } from "./context/CartContext";

// app/layout.js (App Router) or pages/_app.js (Pages Router)

// import { WishlistProvider } from "@/context/WishlistContext";
// import { StoreProvider } from '../context/StoreContext';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
});

export const metadata = {
  title: 'My App',
};


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body style={{backgroundColor: "#1a1a1a"}}> 
        {/* <StoreProvider> */}
         {/* <WishlistProvider> */}
          <BootstrapClient />
         <CartProvider>
        <Navbar />
        {children}
        <Footer />
        </CartProvider>
        {/* </WishlistProvider> */}
        {/* </StoreProvider> */}
      </body>
    </html>
  );
}
